services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      DB_ENGINE: ${DB_ENGINE}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SUPERUSER_NAME: ${SUPERUSER_NAME}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
      SETTINGS_DIR: ${SETTINGS_DIR}
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}